name:                mf-library
version:             0.1.0.0
github:              "daniel-raffler/mf-library"
license:             OtherLicense
author:              "Daniel Raffler"
maintainer:          "daniel-raffler@gmx.de"
copyright:           "Copyright (c) 2022 Daniel Raffler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.

description: Please see the README on GitHub at <https://github.com/daniel-raffler/mf-library#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - zip-archive
  - bytestring
  - containers

library:
  source-dirs: src
